# Site settings
title: Great New Blog Title
author:
  name: Gabriele Hayden
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima:
                       skin: dark
